### ISSUE TITLE
Reprint Labels (L_LABEL_EXPRESS)

### ISSUE THREAD

**Issue by richardiphillips** [linn/stores#399]
We still use

Carton Label
Pallet Label
Address Label
General Label

Hope this helps

Dougy

**Comment by andrewfraser73** [comment]
don't see where this is in the menu or that it has been run recently
there is already a general label printer http://app.linn.co.uk/production/maintenance/labels/print which does this

**Comment by andrewfraser73** [comment]
From memory some of the occasional consignment labels are printed with it but if it's already been done then we should track it down and destroy it

**Comment by andrewfraser73** [comment]
Actually it's not the general label printer it is the l_label_express despatch labels printing need to figure out how it works from consignment and make a new version for doing 
Pallet
Address
General

possibly link to from consignment screen
